apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: prod
  name: archgen-prod-api-gateway-keyvault-provider
spec:
  provider: azure
  secretObjects:
    - secretName: archgen-prod-api-gateway-secrets
      type: Opaque
      data:
        - objectName: GATEWAY_PORT
          key: GATEWAY_PORT
        - objectName: PRODUCTION_ORIGIN
          key: PRODUCTION_ORIGIN
        - objectName: AUTH_SERVICE_URL
          key: AUTH_SERVICE_URL
        - objectName: PROJECT_SERVICE_URL
          key: PROJECT_SERVICE_URL
        - objectName: ARCHITECTURE_SERVICE_URL
          key: ARCHITECTURE_SERVICE_URL
        - objectName: ALLOWED_ORIGINS
          key: ALLOWED_ORIGINS
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "1e9e4c11-d7fb-448f-b440-6e1ea1993bf4"
    keyvaultName: "kvpraveen"
    objects: |
      array:
        - |
          objectName: prod-gateway-port
          objectType: secret
          objectAlias: GATEWAY_PORT
        - |
          objectName: prod-production-origin
          objectType: secret
          objectAlias: PRODUCTION_ORIGIN
        - |
          objectName: prod-auth-service-url
          objectType: secret
          objectAlias: AUTH_SERVICE_URL
        - |
          objectName: prod-project-service-url
          objectType: secret
          objectAlias: PROJECT_SERVICE_URL
        - |
          objectName: prod-architecture-service-url
          objectType: secret
          objectAlias: ARCHITECTURE_SERVICE_URL
        - |
          objectName: prod-allowed-origins
          objectType: secret
          objectAlias: ALLOWED_ORIGINS
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
