apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: prod
  name: archgen-prod-project-service-keyvault-provider
spec:
  provider: azure
  secretObjects:
    - secretName: archgen-prod-project-service-secrets
      type: Opaque
      data:
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: DATABASE_NAME
          key: DATABASE_NAME
        - objectName: ALLOWED_ORIGINS
          key: ALLOWED_ORIGINS
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "1e9e4c11-d7fb-448f-b440-6e1ea1993bf4"
    keyvaultName: "kvpraveen"
    objects: |
      array:
        - |
          objectName: prod-jwt-secret
          objectType: secret
          objectAlias: JWT_SECRET_KEY
        - |
          objectName: prod-cosmos-connection-string
          objectType: secret
          objectAlias: MONGO_URI
        - |
          objectName: prod-database-name
          objectType: secret
          objectAlias: DATABASE_NAME
        - |
          objectName: prod-allowed-origins
          objectType: secret
          objectAlias: ALLOWED_ORIGINS
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
