replicaCount: 2
image:
  repository: acrarchgen.azurecr.io/frontend
  pullPolicy: IfNotPresent
  tag: "sha-c60697a"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: dev.printnow.space
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
