replicaCount: 1
image:
  repository: acrarchgen.azurecr.io/frontend
  pullPolicy: IfNotPresent
  tag: "sha-f00f751-temp"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx-dev"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
