apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dev
  name: archgen-dev-auth-service-sa
  annotations:
    azure.workload.identity/client-id: "7d243029-8f47-4b54-800b-b9d8c2c6c70a"
  labels:
    app: auth-service
