apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: prod
  name: archgen-prod-auth-service-keyvault-provider
spec:
  provider: azure
  secretObjects:
    - secretName: archgen-prod-auth-service-secrets
      type: Opaque
      data:
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: DATABASE_NAME
          key: DATABASE_NAME
        - objectName: JWT_ALGORITHM
          key: JWT_ALGORITHM
        - objectName: ACCESS_TOKEN_EXPIRE_MINUTES
          key: ACCESS_TOKEN_EXPIRE_MINUTES
        - objectName: REFRESH_TOKEN_EXPIRE_DAYS
          key: REFRESH_TOKEN_EXPIRE_DAYS
        - objectName: ALLOWED_ORIGINS
          key: ALLOWED_ORIGINS
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6f0a06df-ee8c-4ba1-bef1-4107a8a7ddbf"
    keyvaultName: "kvarchgenprod"
    objects: |
      array:
        - |
          objectName: prod-jwt-secret
          objectType: secret
          objectAlias: JWT_SECRET_KEY
        - |
          objectName: prod-cosmos-connection-string
          objectType: secret
          objectAlias: MONGO_URI
        - |
          objectName: prod-database-name
          objectType: secret
          objectAlias: DATABASE_NAME
        - |
          objectName: prod-jwt-algorithm
          objectType: secret
          objectAlias: JWT_ALGORITHM
        - |
          objectName: prod-access-token-expire-minutes
          objectType: secret
          objectAlias: ACCESS_TOKEN_EXPIRE_MINUTES
        - |
          objectName: prod-refresh-token-expire-days
          objectType: secret
          objectAlias: REFRESH_TOKEN_EXPIRE_DAYS
        - |
          objectName: prod-allowed-origins
          objectType: secret
          objectAlias: ALLOWED_ORIGINS
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
