replicaCount: 2

image:
  repository: acrarchgen.azurecr.io/api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/rule-type: "path"
  hosts:
    - host: api.archgen.com
      paths:
        - path: /api/
          pathType: Prefix

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

config:
  GATEWAY_PORT: "8080"
  PRODUCTION_ORIGIN: "https://api.archgen.com"
  AUTH_SERVICE_URL: "http://archgen-prod-auth-service:8001"
  PROJECT_SERVICE_URL: "http://archgen-prod-project-service:8002"
  ARCHITECTURE_SERVICE_URL: "http://archgen-prod-architecture-service:8003"
  ALLOWED_ORIGINS: "http://localhost:3000,http://20.51.185.99:3000"

nodeSelector: {}
tolerations: []
affinity: {}
