replicaCount: 2

image:
  repository: acrarchgen.azurecr.io/api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  hosts:
    - host: prod.archgen.com
      paths:
        - path: /api
          pathType: Prefix
    - host: api.archgen.com
      paths:
        - path: /api
          pathType: Prefix
    - host: archgen.com
      paths:
        - path: /api
          pathType: Prefix

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

config: {}
keyvault:
  enabled: true
  name: "kvpraveen"
  clientId: "1e9e4c11-d7fb-448f-b440-6e1ea1993bf4"
  tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
  secrets:
    - name: "prod-gateway-port"
      alias: "GATEWAY_PORT"
    - name: "prod-production-origin"
      alias: "PRODUCTION_ORIGIN"
    - name: "prod-auth-service-url"
      alias: "AUTH_SERVICE_URL"
    - name: "prod-project-service-url"
      alias: "PROJECT_SERVICE_URL"
    - name: "prod-architecture-service-url"
      alias: "ARCHITECTURE_SERVICE_URL"
    - name: "prod-allowed-origins"
      alias: "ALLOWED_ORIGINS"

nodeSelector: {}
tolerations: []
affinity: {}
