replicaCount: 1
image:
  repository: acrarchgen.azurecr.io/api-gateway
  pullPolicy: IfNotPresent
  tag: "sha-693f183"
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/rule-type: "path"
  hosts:
    - host: api-dev.archgen.com
      paths:
        - path: /api/
          pathType: Prefix
resources:
  limits:
    cpu: 150m
    memory: 256Mi
  requests:
    cpu: 75m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
config:
  GATEWAY_PORT: "8080"
  PRODUCTION_ORIGIN: "https://api-dev.archgen.com"
  AUTH_SERVICE_URL: "http://archgen-dev-auth-service:8001"
  PROJECT_SERVICE_URL: "http://archgen-dev-project-service:8002"
  ARCHITECTURE_SERVICE_URL: "http://archgen-dev-architecture-service:8003"
  ALLOWED_ORIGINS: "http://localhost:3000,http://20.51.185.99:3000"

nodeSelector: {}
tolerations: []
affinity: {}
