replicaCount: 1
image:
  repository: acrarchgen.azurecr.io/api-gateway
  pullPolicy: IfNotPresent
  tag: "sha-33a3891"
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "nginx-dev"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
resources:
  limits:
    cpu: 150m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
config: {}
keyvault:
  enabled: true
  name: "kvarchgen"
  clientId: "7d243029-8f47-4b54-800b-b9d8c2c6c70a"
  tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
  secrets:
    - name: "dev-gateway-port"
      alias: "GATEWAY_PORT"
    - name: "dev-production-origin"
      alias: "PRODUCTION_ORIGIN"
    - name: "dev-auth-service-url"
      alias: "AUTH_SERVICE_URL"
    - name: "dev-project-service-url"
      alias: "PROJECT_SERVICE_URL"
    - name: "dev-architecture-service-url"
      alias: "ARCHITECTURE_SERVICE_URL"
    - name: "dev-allowed-origins"
      alias: "ALLOWED_ORIGINS"
nodeSelector: {}
tolerations: []
affinity: {}
