replicaCount: 1

image:
  repository: acrarchgen.azurecr.io/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8001

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

config: {}

keyvault:
  enabled: true
  name: "kvarchgenprod"
  clientId: "6f0a06df-ee8c-4ba1-bef1-4107a8a7ddbf"
  tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
  secrets:
    - name: "prod-database-name"
      alias: "DATABASE_NAME"
    - name: "prod-jwt-algorithm"
      alias: "JWT_ALGORITHM"
    - name: "prod-access-token-expire-minutes"
      alias: "ACCESS_TOKEN_EXPIRE_MINUTES"
    - name: "prod-refresh-token-expire-days"
      alias: "REFRESH_TOKEN_EXPIRE_DAYS"
    - name: "prod-allowed-origins"
      alias: "ALLOWED_ORIGINS"
    - name: "prod-jwt-secret"
      alias: "JWT_SECRET_KEY"
    - name: "prod-cosmos-connection-string"
      alias: "MONGO_URI"

nodeSelector: {}
tolerations: []
affinity: {}
