apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dev
  name: archgen-dev-auth-service-sa
  annotations:
    azure.workload.identity/client-id: "1e9e4c11-d7fb-448f-b440-6e1ea1993bf4"
  labels:
    app: auth-service
