apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: dev
  name: archgen-dev-project-service-keyvault-provider
spec:
  provider: azure
  secretObjects:
    - secretName: archgen-dev-project-service-secrets
      type: Opaque
      data:
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: DATABASE_NAME
          key: DATABASE_NAME
        - objectName: ALLOWED_ORIGINS
          key: ALLOWED_ORIGINS
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "7d243029-8f47-4b54-800b-b9d8c2c6c70a"
    keyvaultName: "kvarchgen"
    objects: |
      array:
        - |
          objectName: dev-jwt-secret
          objectType: secret
          objectAlias: JWT_SECRET_KEY
        - |
          objectName: dev-cosmos-connection-string
          objectType: secret
          objectAlias: MONGO_URI
        - |
          objectName: dev-database-name
          objectType: secret
          objectAlias: DATABASE_NAME
        - |
          objectName: dev-allowed-origins
          objectType: secret
          objectAlias: ALLOWED_ORIGINS
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
