apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prod
  name: archgen-prod-project-service-sa
  annotations:
    azure.workload.identity/client-id: "6f0a06df-ee8c-4ba1-bef1-4107a8a7ddbf"
  labels:
    app: project-service
