{{- if .Values.keyvault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-api-gateway-sa
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyvault.clientId | quote }}
  labels:
    app: api-gateway
{{- end }}
